name: manual run

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug  
      
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
         
      - name: get tag name
        if: startsWith(github.ref, 'refs/heads/main')
        run: echo "TAG=latest" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags')
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV
      
      - name: build & push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/msrevive/image:${{ env.TAG }}  