name: manual run

on:
  workflow_dispatch:
  paths-ignore:
    - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - run: echo "TAG=latest" >> $GITHUB_ENV
    
    - name: build & push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
     